language: node_js
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"
before_install:
  - npm install -g npm@latest
  - npm ci
script:
  - lerna bootstrap
  - npm test
